name: ChestRandomizer
version: 4.0-SNAPSHOT
main: com.abstractionalpha.minecraft.plugins.chestrandomizer.manager.ChestRandomizer
api-version: 1.16
authors: [abstractionAlpha]
description: Random loot for chests. Useful for survival games,
commands:
  cr:
    description: Root command. Lists all command options.
    usage: /<command>
    permission: chestrandomizer.cr
    permission-message: You do not have <permission>.
